import type { Module } from '../types'
import { plainColours } from '../figure-palette'
import { module1 } from './m1-bilangan-cacah'
import { module2 } from './m2-faktor-kelipatan'
import { module3 } from './m3-pecahan'
import { module4 } from './m4-desimal-persen'
import { module5 } from './m5-panjang-berat-volume'
import { module6 } from './m6-waktu-kecepatan'
import { module7 } from './m7-sudut-penaksiran'
import { module8 } from './m8-bangun-datar'
import { module9 } from './m9-bangun-ruang'
import { module10 } from './m10-data'
import { module11 } from './m11-strategi-simulasi'

export const modules: Module[] = plainColours([module1, module2, module3, module4, module5, module6, module7, module8, module9, module10, module11])
